# Generated by Django 5.1.2 on 2025-01-16 23:51

import core.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_remove_user_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='is_instructional',
            field=models.BooleanField(help_text='Whether or not school is running on this day. Automatically changes depending on the schedule format and should not be manually edited.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether or not this event is viewable to the general school population, not just those in the organization.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='should_announce',
            field=models.BooleanField(default=False, help_text='Whether or not this event should be announced to the general school population VIA the important events feed.'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='years',
            field=core.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')]), help_text='The years the user was a staff member. Used to determine if the user is an alumni.', size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='graduating_year',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Does not apply'), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028)], null=True),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_archived'], name='core_blogpo_is_arch_6e9c26_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_published'], name='core_blogpo_is_publ_bed51c_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['created_date'], name='idx_created_date'),
        ),
    ]
