# Generated by Django 5.1.5 on 2025-01-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_dailyannouncement_alter_event_is_instructional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gcal_etag',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='gcal_id',
            field=models.CharField(default=None, max_length=1024, null=True, unique=True),
        ),
    ]
